---
# tasks file for gce_instance

  - name: Create VM instance for "{{ gce_app }}"
    delegate_to: localhost
    gce:
      instance_names: "{{ gce_vms }}"
      machine_type: "{{ vm_type }}"
      image: "{{ vm_image }}"
      state: present
      tags: "{{ gce_app }}"
      service_account_email: "{{ service_account }}"
      credentials_file: "{{ credentials }}"
      project_id: "{{ project }}"
    register: gce
  - name: spit out IP
    debug:
      msg: "here is the IP {{ item.public_ip }}"
    with_items: "{{ gce.instance_data }}"
