---
# tasks file for gce_instance

  - name: Create VM instance for "{{ gce_app }}"
    gce:
      instance_names: "{{ gce_vms }}"
      machine_type: "{{ vm_type }}"
      image: "{{ vm_image }}"
      state: present
      tags: "{{ gce_app }}"
      service_account_email: "{{ service_account }}"
      credentials_file: "{{ credentials }}"
      project_id: "{{ project }}"
